# -*- coding: utf-8 -*-
"""Information Retrieval model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w6mIF5hUPPSKKjIY7K3UhdPtBiSgmjwx
"""

import pandas as pd
import nltk
nltk.download('stopwords')

# model 1
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer

data = pd.DataFrame({
    'answers': ['Laravel is a PHP framework that provides tools and resources to build modern PHP applications.',
                'You can install Laravel via Composer by running the command: composer create-project --prefer-dist laravel/laravel project-name.'
               'Facades in Laravel provide a static-like interface to classes that are available in the application’s service container.',
                'Eloquent ORM is Laravel’s built-in ORM that provides an ActiveRecord implementation to work with your database.',
                'You can create a controller using the Artisan command: php artisan make:controller ControllerName.',
                'Middleware in Laravel is a mechanism for filtering HTTP requests entering your application.',
                'Migrations are used to create, modify, and share the application’s database schema. Use php artisan make:migration to create a new migration.',
                'Service Providers are the central place of all Laravel application bootstrapping. They are used to bind services into the service container.',
                'Blade is Laravel’s powerful templating engine that allows you to write plain PHP code in your views. Use @extends, @section, and @yield directives for layouts.',
                'Laravel Mix provides a clean, fluent API for defining Webpack build steps for your Laravel application.',
                'This is a sample answer for Laravel question 100.']
})
def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)
    tokens = word_tokenize(text)
    tokens = [word for word in tokens if word not in stopwords.words('english')]
    return ' '.join(tokens)

data['processed_answers'] = data['answers'].apply(preprocess_text)
vectorizer = TfidfVectorizer()
answer_vectors = vectorizer.fit_transform(data['processed_answers'])

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

model = SentenceTransformer('paraphrase-MiniLM-L6-v2')

answer_embeddings = model.encode(data['answers'])

def get_answer_sbert(question):
    question_embedding = model.encode([question])

    similarities = cosine_similarity(question_embedding, answer_embeddings)

    best_match_index = similarities.argmax()

    return data['answers'].iloc[best_match_index]

inp=input("enter your question: ")
print(get_answer_sbert(inp))

# model 2
import pandas as pd
import torch
from sentence_transformers import SentenceTransformer

data = pd.DataFrame({
    'answers': ['Laravel is a PHP framework that provides tools and resources to build modern PHP applications.',
                'You can install Laravel via Composer by running the command: composer create-project --prefer-dist laravel/laravel project-name.'
               'Facades in Laravel provide a static-like interface to classes that are available in the application’s service container.',
                'Eloquent ORM is Laravel’s built-in ORM that provides an ActiveRecord implementation to work with your database.',
                'You can create a controller using the Artisan command: php artisan make:controller ControllerName.',
                'Middleware in Laravel is a mechanism for filtering HTTP requests entering your application.',
                'Migrations are used to create, modify, and share the application’s database schema. Use php artisan make:migration to create a new migration.',
                'Service Providers are the central place of all Laravel application bootstrapping. They are used to bind services into the service container.',
                'Blade is Laravel’s powerful templating engine that allows you to write plain PHP code in your views. Use @extends, @section, and @yield directives for layouts.',
                'Laravel Mix provides a clean, fluent API for defining Webpack build steps for your Laravel application.',
                'This is a sample answer for Laravel question 100.']
})

model = SentenceTransformer('distilbert-base-nli-stsb-mean-tokens')

answer_embeddings = model.encode(data['answers'], convert_to_tensor=True)

def retrieve_similar_answer(question):
    question_embedding = model.encode([question], convert_to_tensor=True)
    similarities = torch.nn.functional.cosine_similarity(question_embedding, answer_embeddings)
    best_match_idx = torch.argmax(similarities).item()
    return data['answers'].iloc[best_match_idx], similarities[best_match_idx].item()

def generate_refined_answer(question):
    retrieved_answer, similarity = retrieve_similar_answer(question)
    refined_answer = f"Answer: {retrieved_answer} (Similarity: {similarity:.2f})"
    return refined_answer

input12=input("enter your question?")
print(generate_refined_answer(input12))
print(generate_refined_answer(input12))

# model 3
!pip install transformers faiss-gpu
from transformers import DPRQuestionEncoder, DPRQuestionEncoderTokenizer, DPRContextEncoder, DPRContextEncoderTokenizer
import torch
import pandas as pd

data = pd.DataFrame({
    'answers': ['Laravel is a PHP framework that provides tools and resources to build modern PHP applications.',
                'You can install Laravel via Composer by running the command: composer create-project --prefer-dist laravel/laravel project-name.'
               'Facades in Laravel provide a static-like interface to classes that are available in the application’s service container.',
                'Eloquent ORM is Laravel’s built-in ORM that provides an ActiveRecord implementation to work with your database.',
                'You can create a controller using the Artisan command: php artisan make:controller ControllerName.',
                'Middleware in Laravel is a mechanism for filtering HTTP requests entering your application.',
                'Migrations are used to create, modify, and share the application’s database schema. Use php artisan make:migration to create a new migration.',
                'Service Providers are the central place of all Laravel application bootstrapping. They are used to bind services into the service container.',
                'Blade is Laravel’s powerful templating engine that allows you to write plain PHP code in your views. Use @extends, @section, and @yield directives for layouts.',
                'Laravel Mix provides a clean, fluent API for defining Webpack build steps for your Laravel application.',
                'This is a sample answer for Laravel question 100.']
})
question_encoder = DPRQuestionEncoder.from_pretrained("facebook/dpr-question_encoder-single-nq-base")
question_tokenizer = DPRQuestionEncoderTokenizer.from_pretrained("facebook/dpr-question_encoder-single-nq-base")
context_encoder = DPRContextEncoder.from_pretrained("facebook/dpr-ctx_encoder-single-nq-base")
context_tokenizer = DPRContextEncoderTokenizer.from_pretrained("facebook/dpr-ctx_encoder-single-nq-base")

context_inputs = context_tokenizer(data['answers'].tolist(), return_tensors='pt', padding=True, truncation=True)
answer_embeddings = context_encoder(**context_inputs).pooler_output

def encode_question(question):
    question_inputs = question_tokenizer(question, return_tensors='pt', padding=True, truncation=True)
    question_embedding = question_encoder(**question_inputs).pooler_output
    return question_embedding

def retrieve_dpr_similar_answer(question):
    question_embedding = encode_question(question)
    similarities = torch.nn.functional.cosine_similarity(question_embedding, answer_embeddings)
    best_match_idx = torch.argmax(similarities).item()

    return data['answers'].iloc[best_match_idx], similarities[best_match_idx].item()

user_question = input('question?')
print(retrieve_dpr_similar_answer(user_question))

# model 4
!pip install rank_bm25
from rank_bm25 import BM25Okapi
import pandas as pd

data = pd.DataFrame({
    'answers': ['Laravel is a PHP framework that provides tools and resources to build modern PHP applications.',
                'You can install Laravel via Composer by running the command: composer create-project --prefer-dist laravel/laravel project-name.'
               'Facades in Laravel provide a static-like interface to classes that are available in the application’s service container.',
                'Eloquent ORM is Laravel’s built-in ORM that provides an ActiveRecord implementation to work with your database.',
                'You can create a controller using the Artisan command: php artisan make:controller ControllerName.',
                'Middleware in Laravel is a mechanism for filtering HTTP requests entering your application.',
                'Migrations are used to create, modify, and share the application’s database schema. Use php artisan make:migration to create a new migration.',
                'Service Providers are the central place of all Laravel application bootstrapping. They are used to bind services into the service container.',
                'Blade is Laravel’s powerful templating engine that allows you to write plain PHP code in your views. Use @extends, @section, and @yield directives for layouts.',
                'Laravel Mix provides a clean, fluent API for defining Webpack build steps for your Laravel application.',
                'This is a sample answer for Laravel question 100.']
})

tokenized_answers = [answer.split() for answer in data['answers'].tolist()]

bm25 = BM25Okapi(tokenized_answers)

def retrieve_bm25_answer(question):
    tokenized_question = question.split()
    scores = bm25.get_scores(tokenized_question)

    best_match_idx = scores.argmax()

    return data['answers'].iloc[best_match_idx], scores[best_match_idx]
quest = input("question?")
print(retrieve_bm25_answer(quest))

# model 5
from sentence_transformers import CrossEncoder

data = pd.DataFrame({
    'answers': ['Laravel is a PHP framework that provides tools and resources to build modern PHP applications.',
                'You can install Laravel via Composer by running the command: composer create-project --prefer-dist laravel/laravel project-name.'
               'Facades in Laravel provide a static-like interface to classes that are available in the application’s service container.',
                'Eloquent ORM is Laravel’s built-in ORM that provides an ActiveRecord implementation to work with your database.',
                'You can create a controller using the Artisan command: php artisan make:controller ControllerName.',
                'Middleware in Laravel is a mechanism for filtering HTTP requests entering your application.',
                'Migrations are used to create, modify, and share the application’s database schema. Use php artisan make:migration to create a new migration.',
                'Service Providers are the central place of all Laravel application bootstrapping. They are used to bind services into the service container.',
                'Blade is Laravel’s powerful templating engine that allows you to write plain PHP code in your views. Use @extends, @section, and @yield directives for layouts.',
                'Laravel Mix provides a clean, fluent API for defining Webpack build steps for your Laravel application.',
                'This is a sample answer for Laravel question 100.']
})

cross_encoder = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-12-v2')

def retrieve_cross_encoder_answer(question):

    pairs = [(question, answer) for answer in data['answers']]
    scores = cross_encoder.predict(pairs)
    best_match_idx = scores.argmax()

    return data['answers'].iloc[best_match_idx], scores[best_match_idx]
ques = input("question?")
print(retrieve_cross_encoder_answer(ques))

